// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "Demo showing how next-intl static rendering setup with generateStaticParams() and setRequestLocale() enables Next.js 16 cacheComponents. Page extracts locale from params and passes it explicitly to cached components.",
    "title": "cacheComponents with next-intl",
    "dynamicComponent": {
      "title": "Dynamic Component",
      "content": "Uses getTranslations('IndexPage') with only namespace parameter, which internally reads from headers(). This component is not cacheable and runs on every request."
    },
    "link": "Go to Pathnames page",
    "cachedComponent": {
      "title": "Cached Component",
      "content": "Receives locale from params (generated by generateStaticParams()) as prop and uses getTranslations with explicit locale. Works with 'use cache' because locale is passed explicitly, not read from headers()."
    }
  },
  "LocaleLayout": {
    "title": "cacheComponents with next-intl"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, de {Deutsch} en {English} other {Unknown}}"
  },
  "Manifest": {
    "name": "cacheComponents with next-intl"
  },
  "Navigation": {
    "home": "Home",
    "pathnames": "Pathnames"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Browse the cacheComponents implementation on GitHub.",
        "href": "https://github.com/aurorascharff/next-intl-cache-components/blob/main/src/app/%5Blocale%5D/page.tsx",
        "title": "GitHub"
      },
      "source": {
        "description": "Learn about next-intl static rendering setup.",
        "href": "https://next-intl.dev/docs/routing/setup#static-rendering",
        "title": "Documentation"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  }
};
export default messages;