import type { Metadata } from "next";
import "./globals.css";
import { SnackbarProvider } from "./context/SnackbarContext";

export const metadata: Metadata = {
  title: "Tsvetomir's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SnackbarProvider>
        <body className="dark:bg-slate-800" suppressHydrationWarning={true}>
          {children}
        </body>
      </SnackbarProvider>
    </html>
  );
}
