import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar";

export const metadata: Metadata = {
  title: "Tsvetomir's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-slate-800">
        <NavBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
