import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/header";
import { AudioEngineProvider } from "./_contexts/audio-engine";
import styles from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const containerClassName = [
  "alternative-theme-override",
  styles.container,
].join(" ");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={containerClassName}>
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
