apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: podkrepibg

resources:
- ../../base

patches:
- path: manual/keycloak-config-web.patch.yaml
- path: manual/deployment.patch.yaml

images:
- name: ghcr.io/podkrepi-bg/frontend
  newName: ghcr.io/podkrepi-bg/frontend
  newTag: master
- name: ghcr.io/podkrepi-bg/frontend/maintenance
  newTag: master
